### ISSUE TITLE
Last buffer block doesn't get split into lines.

### ISSUE THREAD

**Issue by kiwiroy** [Grinnz/Mojo-IOLoop-Stream-Role-LineBuffer#3]
Should the last buffer get split into lines?

https://github.com/Grinnz/Mojo-IOLoop-Stream-Role-LineBuffer/blob/ba676a632de4ecbd087fe213870fcecafd74a7ab/lib/Mojo/IOLoop/Stream/Role/LineBuffer.pm#L29-L34

**Comment by Grinnz** [comment]
Good catch!

**Comment by kiwiroy** [comment]
I have e4ba6bd, which passes current tests. I don't currently have a good test for the change though.

**Comment by Grinnz** [comment]
It seems only possible to happen if the line separator is changed after reading and before the close event. Should be fixed by https://github.com/Grinnz/Mojo-IOLoop-Stream-Role-LineBuffer/commit/5f89b205336a3d06a581e6cacb436b88bca5e632

**Comment by kiwiroy** [comment]
Yes, that's fixed it. Thanks
