### ISSUE TITLE
closing the stream from read_line handler

### ISSUE THREAD

**Issue by Yenya** [Grinnz/Mojo-IOLoop-Stream-Role-LineBuffer#4]
When I try to `$stream->close` the LineBuffer stream from the inside of the `read_line` event handler, I got the last line once again (one more `read_line` gets emitted), and some undefined value warnings. It is because `LineBuffer.pm` deletes `_read_line_buffer` from the `close` event handler, but tries to send the rest of the buffer once again.

Sample code:

[stream.pl.txt](https://github.com/Grinnz/Mojo-IOLoop-Stream-Role-LineBuffer/files/7477044/stream.pl.txt)

Output:
```
$ ./stream.pl
new client accepted
got stop
got stop
Use of uninitialized value in pattern match (m//) at /home/kas/perl5/lib/perl5/Mojo/IOLoop/Stream/Role/LineBuffer.pm line 20.
Use of uninitialized value in substr at /home/kas/perl5/lib/perl5/Mojo/IOLoop/Stream/Role/LineBuffer.pm line 26.
substr outside of string at /home/kas/perl5/lib/perl5/Mojo/IOLoop/Stream/Role/LineBuffer.pm line 26.
```

**Comment by Grinnz** [comment]
This should be fixed in 0.007. Thanks!
